#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 07, 2020 01:52:55 PM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import add_student_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    add_student_support.set_Tk_var()
    top = Toplevel1 (root)
    add_student_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    add_student_support.set_Tk_var()
    top = Toplevel1 (w)
    add_student_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Yu Gothic UI Semibold} -size 11 -weight "  \
            "bold"
        font11 = "-family {Yu Gothic UI Semibold} -size 12 -weight "  \
            "bold"
        font12 = "-family {Segoe UI Emoji} -size 13 -weight bold"
        font9 = "-family {Yu Gothic UI Semibold} -size 13 -weight bold"  \
            ""
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("742x606+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Attendance - Add Student")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.015, relwidth=1.004)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#00ffff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.107, rely=0.211, height=46, width=172)
        self.Label1.configure(background="#00ffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Student Name''')

        self.txtName = tk.Entry(self.Frame1)
        self.txtName.place(relx=0.362, rely=0.228,height=44, relwidth=0.515)
        self.txtName.configure(background="white")
        self.txtName.configure(borderwidth="2")
        self.txtName.configure(disabledforeground="#a3a3a3")
        self.txtName.configure(font=font10)
        self.txtName.configure(foreground="#000000")
        self.txtName.configure(insertbackground="black")

        self.Label1_1 = tk.Label(self.Frame1)
        self.Label1_1.place(relx=0.081, rely=0.374, height=46, width=202)
        self.Label1_1.configure(activebackground="#f9f9f9")
        self.Label1_1.configure(activeforeground="black")
        self.Label1_1.configure(background="#00ffff")
        self.Label1_1.configure(disabledforeground="#a3a3a3")
        self.Label1_1.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1_1.configure(foreground="#000000")
        self.Label1_1.configure(highlightbackground="#d9d9d9")
        self.Label1_1.configure(highlightcolor="black")
        self.Label1_1.configure(text='''Student Class''')

        self.comboClass = ttk.Combobox(self.Frame1)
        self.comboClass.place(relx=0.362, rely=0.374, relheight=0.076
                , relwidth=0.518)
        self.value_list = ['Select Class',]
        self.comboClass.configure(values=self.value_list)
        self.comboClass.configure(font=font11)
        self.comboClass.configure(state='readonly')
        self.comboClass.configure(textvariable=add_student_support.combobox)
        self.comboClass.configure(takefocus="")
        self.comboClass.current(0)

        self.btnTakePic = tk.Button(self.Frame1)
        self.btnTakePic.place(relx=0.362, rely=0.52, height=53, width=166)
        self.btnTakePic.configure(activebackground="#ececec")
        self.btnTakePic.configure(activeforeground="#000000")
        self.btnTakePic.configure(background="#eac515")
        self.btnTakePic.configure(borderwidth="3")
        self.btnTakePic.configure(disabledforeground="#a3a3a3")
        self.btnTakePic.configure(font=font12)
        self.btnTakePic.configure(foreground="#000000")
        self.btnTakePic.configure(highlightbackground="#d9d9d9")
        self.btnTakePic.configure(highlightcolor="black")
        self.btnTakePic.configure(pady="0")
        self.btnTakePic.configure(text='''Take Picture''')

        self.Label1_4 = tk.Label(self.Frame1)
        self.Label1_4.place(relx=0.107, rely=0.52, height=46, width=172)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#00ffff")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Student Picture''')

        self.btnAdd = tk.Button(self.Frame1)
        self.btnAdd.place(relx=0.362, rely=0.699, height=53, width=386)
        self.btnAdd.configure(activebackground="#ececec")
        self.btnAdd.configure(activeforeground="#000000")
        self.btnAdd.configure(background="#eac515")
        self.btnAdd.configure(borderwidth="3")
        self.btnAdd.configure(disabledforeground="#a3a3a3")
        self.btnAdd.configure(font="-family {Segoe UI Emoji} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnAdd.configure(foreground="#000000")
        self.btnAdd.configure(highlightbackground="#d9d9d9")
        self.btnAdd.configure(highlightcolor="black")
        self.btnAdd.configure(pady="0")
        self.btnAdd.configure(text='''Add''')

        self.btnBrowsePic = tk.Button(self.Frame1)
        self.btnBrowsePic.place(relx=0.631, rely=0.52, height=53, width=186)
        self.btnBrowsePic.configure(activebackground="#ececec")
        self.btnBrowsePic.configure(activeforeground="#000000")
        self.btnBrowsePic.configure(background="#eac515")
        self.btnBrowsePic.configure(borderwidth="3")
        self.btnBrowsePic.configure(disabledforeground="#a3a3a3")
        self.btnBrowsePic.configure(font="-family {Segoe UI Emoji} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnBrowsePic.configure(foreground="#000000")
        self.btnBrowsePic.configure(highlightbackground="#d9d9d9")
        self.btnBrowsePic.configure(highlightcolor="black")
        self.btnBrowsePic.configure(pady="0")
        self.btnBrowsePic.configure(text='''Browse Picture''')

if __name__ == '__main__':
    vp_start_gui()





