#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 07, 2020 10:38:18 PM IST  platform: Windows NT

import sys
import model
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import add_subject_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    add_subject_support.set_Tk_var()
    top = addSubject (root)
    add_subject_support.init(root, top)
    root.mainloop()

w = None
def create_addSubject(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_addSubject(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    add_subject_support.set_Tk_var()
    top = addSubject (w)
    add_subject_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_addSubject():
    global w
    w.destroy()
    w = None

class addSubject:
    def addSubject(self):
        name = self.txtSubName.get()
        cls = self.comboClass.get()

        if name != "" and cls != "Select Class":
            isub = model.insertSubject(name, cls)
            if isub:
                messagebox.showinfo("Attendance - Add Subject", "Subject added succesfully!", master=root)
                self.txtSubName.configure(text="")
                self.comboClass.current(0)
            else:
                messagebox.showwarning("Attendance - Add Subject", "Failed to add subject or subject already exists!",
                                       master=root)
        else:
            messagebox.showwarning("Attendance - Add Subject", "Subject Name and class field is required!", master=root)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("841x624+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Attendance - Add Subject")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.006, relwidth=1.005)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#00ffff")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.133, rely=0.217, height=55, width=163)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#00ffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Subject Name''')

        self.txtSubName = tk.Entry(self.Frame1)
        self.txtSubName.place(relx=0.359, rely=0.232,height=44, relwidth=0.49)
        self.txtSubName.configure(background="white")
        self.txtSubName.configure(borderwidth="2")
        self.txtSubName.configure(disabledforeground="#a3a3a3")
        self.txtSubName.configure(font="-family {Yu Gothic UI Semibold} -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        self.txtSubName.configure(foreground="#000000")
        self.txtSubName.configure(highlightbackground="#d9d9d9")
        self.txtSubName.configure(highlightcolor="black")
        self.txtSubName.configure(insertbackground="black")
        self.txtSubName.configure(selectbackground="blue")
        self.txtSubName.configure(selectforeground="white")

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.12, rely=0.389, height=54, width=174)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#00ffff")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Class Name''')

        self.comboClass = ttk.Combobox(self.Frame1)
        self.comboClass.place(relx=0.359, rely=0.403, relheight=0.072
                , relwidth=0.498)
        self.value_list = ['Select Class']
        model.readAllClass(self.value_list)
        self.comboClass.configure(values=self.value_list)
        self.comboClass.configure(font="-family {Yu Gothic UI Semibold} -size 12 -weight bold -slant roman -underline 0 -overstrike 0")
        self.comboClass.configure(state='readonly')
        self.comboClass.configure(textvariable=add_subject_support.combobox)
        self.comboClass.configure(takefocus="")
        self.comboClass.current(0)

        self.btnAddSub = tk.Button(self.Frame1)
        self.btnAddSub.place(relx=0.37, rely=0.557, height=63, width=406)
        self.btnAddSub.configure(activebackground="#ececec")
        self.btnAddSub.configure(activeforeground="#000000")
        self.btnAddSub.configure(background="#eac515")
        self.btnAddSub.configure(borderwidth="3")
        self.btnAddSub.configure(disabledforeground="#a3a3a3")
        self.btnAddSub.configure(font="-family {Segoe UI Emoji} -size 12 -weight bold -slant roman -underline 0 -overstrike 0")
        self.btnAddSub.configure(foreground="#000000")
        self.btnAddSub.configure(highlightbackground="#d9d9d9")
        self.btnAddSub.configure(highlightcolor="black")
        self.btnAddSub.configure(pady="0")
        self.btnAddSub.configure(text='''Add''')
        self.btnAddSub.configure(command=self.addSubject)

if __name__ == '__main__':
    vp_start_gui()





