#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Mar 30, 2021 03:41:39 PM IST  platform: Windows NT

import sys
import model
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import edit_subject_support
import view_subject_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    edit_subject_support.set_Tk_var()
    top = Toplevel1 (root)
    edit_subject_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    edit_subject_support.set_Tk_var()
    top = Toplevel1 (w)
    edit_subject_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def editSubject(self):
        name = self.txtSubName.get()
        cls = self.comboCls.get()
        pname = view_subject_support.sval.get()
        pcls = view_subject_support.cval.get()

        if name != "" and cls != "Select Class":
            isub = model.updateSubject(pname, pcls, name, cls)
            if isub:
                messagebox.showinfo("Attendance - Edit Subject", "Subject updated succesfully!", master=root)
                root.destroy()
            else:
                messagebox.showwarning("Attendance - Edit Subject", "Failed to update subject or subject already exists!", master=root)
        else:
            messagebox.showwarning("Attendance - Edit Subject", "Subject Name and class field is required!", master=root)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Yu Gothic UI Semibold} -size 11 -weight "  \
            "bold"
        font11 = "-family {Yu Gothic UI Semibold} -size 12 -weight "  \
            "bold"
        font12 = "-family {Segoe UI Emoji} -size 12 -weight bold"
        font9 = "-family {Yu Gothic UI Semibold} -size 13 -weight bold"  \
            ""
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("722x588+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Attendance - Edit Subject")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.0, rely=0.0, relheight=1.012, relwidth=1.004)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#00ffff")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.132, rely=0.217, height=55, width=163)
        self.Label1.configure(background="#00ffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Subject Name''')

        self.txtSubName = tk.Entry(self.Frame1)
        self.txtSubName.place(relx=0.359, rely=0.232,height=44, relwidth=0.491)
        self.txtSubName.configure(background="white")
        self.txtSubName.configure(borderwidth="2")
        self.txtSubName.configure(disabledforeground="#a3a3a3")
        self.txtSubName.configure(font=font10)
        self.txtSubName.configure(foreground="#000000")
        self.txtSubName.configure(insertbackground="black")
        self.txtSubName.insert(0, view_subject_support.sval.get())

        self.Label1_5 = tk.Label(self.Frame1)
        self.Label1_5.place(relx=0.12, rely=0.388, height=54, width=174)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#00ffff")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Class Name''')

        self.comboCls = ttk.Combobox(self.Frame1)
        self.comboCls.place(relx=0.359, rely=0.403, relheight=0.072
                , relwidth=0.498)
        self.value_list = ['Select Class']
        model.readAllClass(self.value_list)
        i = self.value_list.index(view_subject_support.cval.get())
        self.comboCls.configure(values=self.value_list)
        self.comboCls.configure(state='readonly')
        self.comboCls.configure(font=font11)
        self.comboCls.configure(textvariable=edit_subject_support.combobox)
        self.comboCls.configure(takefocus="")
        self.comboCls.current(i)

        self.btnEditSub = tk.Button(self.Frame1)
        self.btnEditSub.place(relx=0.37, rely=0.556, height=63, width=353)
        self.btnEditSub.configure(activebackground="#ececec")
        self.btnEditSub.configure(activeforeground="#000000")
        self.btnEditSub.configure(background="#eac515")
        self.btnEditSub.configure(borderwidth="3")
        self.btnEditSub.configure(disabledforeground="#a3a3a3")
        self.btnEditSub.configure(font=font12)
        self.btnEditSub.configure(foreground="#000000")
        self.btnEditSub.configure(highlightbackground="#d9d9d9")
        self.btnEditSub.configure(highlightcolor="black")
        self.btnEditSub.configure(pady="0")
        self.btnEditSub.configure(text='''Save''')
        self.btnEditSub.configure(command=self.editSubject)

if __name__ == '__main__':
    vp_start_gui()





