#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Aug 04, 2020 06:14:45 PM IST  platform: Windows NT

import sys
from tkinter import messagebox
import main

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from PIL import Image, ImageTk

import login_support
import os.path

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    root = tk.Tk()
    top = Toplevel1 (root)
    login_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    global prog_location
    prog_call = sys.argv[0]
    prog_location = os.path.split(prog_call)[0]
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    login_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def cancelLogin(self):
        msg = messagebox.askyesno("Attendance Login","Are you sure, you want to cancel login?")
        if(msg):
            exit()

    def loginUser(self):
        username = self.txtUser.get()
        password = self.txtPass.get()
        if username == 'admin' and password == 'kc1234':
            msg = messagebox.showinfo("Attendance Login", "You have logged in Succesfully!")
            if msg:
                root.destroy()
                main.vp_start_gui()
        else:
            messagebox.showwarning("Attendance Login", "Invalid Username or Password!")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Arial} -size 11 -weight bold"
        font11 = "-family {Segoe UI Emoji} -size 12 -weight bold"
        font9 = "-family {Yu Gothic UI Semibold} -size 13 -weight bold"

        top.geometry("814x644+650+150")
        top.minsize(148, 1)
        top.maxsize(1924, 1055)
        top.resizable(1, 1)
        top.title("Attendance Login")
        top.configure(background="#00ffff")

        self.FrameLogin = tk.Frame(top)
        self.FrameLogin.place(relx=0.0, rely=0.0, relheight=1.573
                , relwidth=2.354)
        self.FrameLogin.configure(relief='groove')
        self.FrameLogin.configure(borderwidth="2")
        self.FrameLogin.configure(relief="groove")
        self.FrameLogin.configure(background="#00ffff")

        self.icon = tk.Button(self.FrameLogin)
        self.icon.place(relx=0.167, rely=0.039, height=193, width=166)
        self.icon.configure(activebackground="#ececec")
        self.icon.configure(activeforeground="#000000")
        self.icon.configure(background="#d9d9d9")
        self.icon.configure(disabledforeground="#a3a3a3")
        self.icon.configure(foreground="#000000")
        self.icon.configure(highlightbackground="#d9d9d9")
        self.icon.configure(highlightcolor="black")
        photo_location = os.path.join(prog_location,"Images/login_pro.jpg")
        global _img0
        _img0 = ImageTk.PhotoImage(file=photo_location)
        self.icon.configure(image=_img0)
        self.icon.configure(pady="0")
        self.icon.configure(relief="groove")
        self.icon.configure(text='''Button''')

        self.Label1 = tk.Label(self.FrameLogin)
        self.Label1.place(relx=0.084, rely=0.306, height=36, width=132)
        self.Label1.configure(background="#00ffff")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font9)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Username''')

        self.Label2 = tk.Label(self.FrameLogin)
        self.Label2.place(relx=0.084, rely=0.375, height=36, width=132)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#00ffff")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Password''')

        self.txtUser = tk.Entry(self.FrameLogin)
        self.txtUser.place(relx=0.209, rely=0.306,height=44, relwidth=0.133)
        self.txtUser.configure(background="#ffffffffffff")
        self.txtUser.configure(disabledforeground="#a3a3a3")
        self.txtUser.configure(font=font10)
        self.txtUser.configure(foreground="#000000")
        self.txtUser.configure(insertbackground="black")

        self.txtPass = tk.Entry(self.FrameLogin)
        self.txtPass.place(relx=0.209, rely=0.375,height=44, relwidth=0.133)
        self.txtPass.configure(background="white")
        self.txtPass.configure(disabledforeground="#a3a3a3")
        self.txtPass.configure(font="-family Arial -size 11 -weight bold -slant roman -underline 0 -overstrike 0")
        self.txtPass.configure(foreground="#000000")
        self.txtPass.configure(highlightbackground="#d9d9d9")
        self.txtPass.configure(highlightcolor="black")
        self.txtPass.configure(insertbackground="black")
        self.txtPass.configure(selectbackground="blue")
        self.txtPass.configure(selectforeground="white")

        self.btnLogin = tk.Button(self.FrameLogin)
        self.btnLogin.place(relx=0.078, rely=0.484, height=53, width=206)
        self.btnLogin.configure(activebackground="#ececec")
        self.btnLogin.configure(activeforeground="#000000")
        self.btnLogin.configure(background="#eac515")
        self.btnLogin.configure(disabledforeground="#a3a3a3")
        self.btnLogin.configure(font=font11)
        self.btnLogin.configure(foreground="#000000")
        self.btnLogin.configure(highlightbackground="#d9d9d9")
        self.btnLogin.configure(highlightcolor="black")
        self.btnLogin.configure(pady="0")
        self.btnLogin.configure(text='''Login''')
        self.btnLogin.configure(command=self.loginUser)

        self.btnCancel = tk.Button(self.FrameLogin)
        self.btnCancel.place(relx=0.235, rely=0.484, height=53, width=206)
        self.btnCancel.configure(activebackground="#ececec")
        self.btnCancel.configure(activeforeground="#000000")
        self.btnCancel.configure(background="#eac515")
        self.btnCancel.configure(disabledforeground="#a3a3a3")
        self.btnCancel.configure(font=font11)
        self.btnCancel.configure(foreground="#000000")
        self.btnCancel.configure(highlightbackground="#d9d9d9")
        self.btnCancel.configure(highlightcolor="black")
        self.btnCancel.configure(pady="0")
        self.btnCancel.configure(text='''Cancel''')
        self.btnCancel.configure(command = self.cancelLogin)

if __name__ == '__main__':
    vp_start_gui()





