#############################################################################
# Generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#  Mar 28, 2021 05:38:04 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top59 {base} {
    global vTcl
    if {$base == ""} {
        set base .top59
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m61" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 765x512+650+150
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1030
    wm minsize $top 148 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Attendance"
    vTcl:DefineAlias "$top" "mainTop" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra60 \
        -borderwidth 2 -relief groove -background #00ffff -height 635 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 765 
    vTcl:DefineAlias "$top.fra60" "Frame1" vTcl:WidgetProc "mainTop" 1
    set site_3_0 $top.fra60
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr46 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr46" "scrollClass" vTcl:WidgetProc "mainTop" 1

    $site_3_0.scr46.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI Semibold} -size 12 -weight bold" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr50 \
        -background $vTcl(actual_gui_bg) -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr50" "scrollSubject" vTcl:WidgetProc "mainTop" 1

    $site_3_0.scr50.01 configure -background white \
        -cursor xterm \
        -disabledforeground #a3a3a3 \
        -font "-family {Yu Gothic UI Semibold} -size 12 -weight bold" \
        -foreground black \
        -height 3 \
        -highlightbackground #d9d9d9 \
        -highlightcolor #d9d9d9 \
        -selectbackground blue \
        -selectforeground white \
        -width 10
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #00ffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Lecture Frame} 
    vTcl:DefineAlias "$site_3_0.lab51" "Label1" vTcl:WidgetProc "mainTop" 1
    entry $site_3_0.ent52 \
        -background white -borderwidth 2 -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 244 
    vTcl:DefineAlias "$site_3_0.ent52" "txtLec" vTcl:WidgetProc "mainTop" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #00ffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Teacher Name} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label1_3" vTcl:WidgetProc "mainTop" 1
    entry $site_3_0.ent55 \
        -background white -borderwidth 2 -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 11 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 244 
    vTcl:DefineAlias "$site_3_0.ent55" "txtTeacher" vTcl:WidgetProc "mainTop" 1
    button $site_3_0.but56 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #eac515 -borderwidth 3 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text {Mark Attendance} 
    vTcl:DefineAlias "$site_3_0.but56" "btnAttend" vTcl:WidgetProc "mainTop" 1
    label $site_3_0.lab45 \
        -activebackground #f9f9f9 -activeforeground black -background #00ffff \
        -disabledforeground #a3a3a3 \
        -font {-family {Yu Gothic UI Semibold} -size 13 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Lecture Type} 
    vTcl:DefineAlias "$site_3_0.lab45" "Label1_4" vTcl:WidgetProc "mainTop" 1
    ttk::combobox $site_3_0.tCo46 \
        -values {{Select Type} Lecture Practical Workshop/Seminar} \
        -font {-family {Yu Gothic UI Semibold} -size 12 -weight bold -slant roman -underline 0 -overstrike 0} \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo46" "comboLecType" vTcl:WidgetProc "mainTop" 1
    button $site_3_0.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #eac515 -borderwidth 3 -disabledforeground #a3a3a3 \
        -font {-family {Segoe UI Black} -size 9 -weight bold -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Refresh 
    vTcl:DefineAlias "$site_3_0.but47" "btnRefresh" vTcl:WidgetProc "mainTop" 1
    place $site_3_0.scr46 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.068 -width 0 \
        -relwidth 0.319 -height 0 -relheight 0.407 -anchor nw \
        -bordermode ignore 
    place $site_3_0.scr50 \
        -in $site_3_0 -x 0 -relx 0.026 -y 0 -rely 0.508 -width 0 \
        -relwidth 0.319 -height 0 -relheight 0.407 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.405 -y 0 -rely 0.167 -width 0 \
        -relwidth 0.199 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent52 \
        -in $site_3_0 -x 0 -relx 0.641 -y 0 -rely 0.167 -width 244 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 0 -relx 0.405 -y 0 -rely 0.315 -width 0 \
        -relwidth 0.199 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent55 \
        -in $site_3_0 -x 0 -relx 0.641 -y 0 -rely 0.315 -width 244 \
        -relwidth 0 -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but56 \
        -in $site_3_0 -x 0 -relx 0.523 -y 0 -rely 0.593 -width 236 \
        -relwidth 0 -height 123 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 0 -relx 0.405 -y 0 -rely 0.463 -width 0 \
        -relwidth 0.2 -height 0 -relheight 0.061 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo46 \
        -in $site_3_0 -x 0 -relx 0.641 -y 0 -rely 0.463 -width 0 \
        -relwidth 0.323 -height 0 -relheight 0.067 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 0 -relx 0.261 -y 0 -rely 0.019 -width 66 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
    menu $top.m61 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $top.m61 add cascade \
        -menu "$top.m61.men63" -command {{}} -label View 
    set site_3_0 $top.m61
    menu $site_3_0.men63 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men63 add command \
        -command {#} -label Student 
    $site_3_0.men63 add command \
        -command {#} -label Subject 
    $site_3_0.men63 add command \
        -command {#} -label Class 
    $top.m61 add cascade \
        -menu "$top.m61.men64" -command {{}} -label Add 
    set site_3_0 $top.m61
    menu $site_3_0.men64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(pr,menubgcolor) -font TkMenuFont \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    $site_3_0.men64 add command \
        -command {#} -label Student 
    $site_3_0.men64 add command \
        -command {#} -label Subject 
    $site_3_0.men64 add command \
        -command {#} -label Class 
    $top.m61 add command \
        -command {#} -label Reports 
    $top.m61 add command \
        -command {#} -label {Change Password} 
    $top.m61 add command \
        -command {#} -label Logout 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra60 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1 -height 0 -relheight 1.005 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top59 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

